core/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views.generic.base import TemplateView

from core.views import example_form

urlpatterns = [
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("accounts/", include("users.urls")),
    path("backside/", admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    # you can delete this next one, only to show you the form styles
    path("example-form/", example_form, name="example_form"),
]

if settings.DEBUG:
    urlpatterns = [
        path("__debug__/", include("debug_toolbar.urls")),
    ] + urlpatterns

users/urls.py
from django.urls import include
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path(
        "password-change/", views.PasswordChangeView.as_view(), name="password_change"
    ),
    path(
        "password-change/done/",
        views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path("password-reset/", views.PasswordResetView.as_view(), name="password_reset"),
    path(
        "password-reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/sent/",
        views.PasswordResetSentView.as_view(),
        name="password_reset_sent",
    ),
    path(
        "password-reset/complete/",
        views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("", include("allauth.urls")),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import BaseUserManager
from django.db import models
from django.utils.translation import gettext_lazy as _


class CustomUserManager(BaseUserManager):
    """Email is the unique user identifier for authentication, not username."""

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a user with the given email and password."""
        if not email:
            raise ValueError(_("Users must have an email address"))

        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        """Create and save a superuser with the given email and password."""
        extra_fields.setdefault("is_active", True)
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError(_("Superuser must have is_staff=True"))
        if extra_fields.get("is_superuser") is not True:
            raise ValueError(_("Superuser must have is_superuser=True"))
        return self.create_user(email, password, **extra_fields)


class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)
    username = None

    objects = CustomUserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

users/forms.py
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.forms import UserCreationForm

from .models import CustomUser


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ["email"]


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ["email"]

core/views.py
from django import forms
from django.shortcuts import render


class ExampleForm(forms.Form):
    name = forms.CharField(label="Your name", max_length=100, required=True)
    email = forms.EmailField(label="Your email", max_length=100, required=True)
    message = forms.CharField(label="Your message", max_length=1000)
    is_retired = forms.BooleanField(
        label="Are you retired?",
        required=False,
        help_text="Optional",
    )
    country = forms.ChoiceField(
        label="Your country",
        choices=[
            ("US", "United States"),
            ("CA", "Canada"),
            ("MX", "Mexico"),
        ],
        widget=forms.RadioSelect,
    )
    favorite_scandanavian_country = forms.ChoiceField(
        label="Your favorite Scandinavian country",
        choices=[
            ("SE", "Sweden"),
            ("NO", "Norway"),
            ("FI", "Finland"),
            ("DK", "Denmark"),
        ],
        widget=forms.Select,
    )
    homepage = forms.URLField(
        label="Your homepage",
        max_length=100,
        required=False,
        help_text="Optional",
    )
    favorite_number = forms.IntegerField(
        label="Your favorite number",
        min_value=1,
        max_value=10,
        help_text="Select a number from 1 to 10",
    )
    birthday = forms.DateField(
        label="Your birthday",
        help_text="Select a date",
    )
    wake_up_time = forms.TimeField(
        label="Your preferred wake up time",
        help_text="Select a time",
    )
    event_start = forms.DateTimeField(
        label="Event start",
        help_text="Select a date and time",
    )
    tags = forms.MultipleChoiceField(
        label="Tags",
        choices=[
            ("python", "Python"),
            ("django", "Django"),
            ("javascript", "JavaScript"),
            ("react", "React"),
        ],
        help_text="Select one or more tags",
    )


class BookForm(forms.Form):
    title = forms.CharField(label="Title", max_length=100, required=True)
    author = forms.CharField(label="Author", max_length=100, required=True)
    description = forms.CharField(label="Description", max_length=1000, required=True)


BookFormSet = forms.formset_factory(
    form=BookForm,
    extra=3,
)


def example_form(request):
    if request.method == "POST":
        form = ExampleForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data)
            book_formset = BookFormSet(request.POST)
            if book_formset.is_valid():
                print(book_formset.cleaned_data)
            return render(
                request,
                "example_form.html",
                {"form": form, "book_formset": book_formset},
            )
    else:
        form = ExampleForm()
        book_formset = BookFormSet()
    return render(
        request, "example_form.html", {"form": form, "book_formset": book_formset}
    )

users/views.py
from django.contrib import messages
from django.contrib.auth import views
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic.edit import CreateView

from .forms import CustomUserCreationForm


class LoginView(views.LoginView):
    template_name = "registration/login.html"


class LogoutView(views.LogoutView):
    pass


class PasswordChangeView(views.PasswordChangeView):
    template_name = "registration/password_change_form.html"
    success_url = reverse_lazy("home")

    def get_success_url(self):
        """Add a success message and redirect"""
        messages.success(self.request, _("Password changed successfully"))
        return super().get_success_url()


class PasswordChangeDoneView(views.PasswordChangeDoneView):
    template_name = "registration/password_change_done.html"


# FLOW: Reset -> ResetSent -> ResetConfirm -> ResetComplete
class PasswordResetCompleteView(views.PasswordResetCompleteView):
    template_name = "registration/password_reset_complete.html"


class PasswordResetConfirmView(views.PasswordResetConfirmView):
    template_name = "registration/password_reset_confirm.html"
    success_url = reverse_lazy("accounts:password_reset_complete")


class PasswordResetSentView(views.PasswordResetDoneView):
    template_name = "registration/password_reset_sent.html"


class PasswordResetView(views.PasswordResetView):
    template_name = "registration/password_reset_form.html"
    success_url = reverse_lazy("accounts:password_reset_sent")


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("accounts:login")
    template_name = "registration/signup.html"

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <title>
      {% block title %}
      {% endblock title %}
      | djarter
    </title>
    <meta name="description"
          content="{% block meta_description %}{% endblock meta_description %}">
    <meta name="keywords" content="">
    <link rel="stylesheet" href="{% static 'style.css' %}">
  </head>
  <body>
    {% include "partials/header.html" %}
    <main class="box no-border">
      {% if messages %}
        <div class="messages">
          <ul class="stack">
            {% for message in messages %}
              <li class="box {% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</li>
            {% endfor %}
          </ul>
        </div>
      {% endif %}
      {% block content %}
      {% endblock content %}
    </main>
    {% include "partials/footer.html" %}
  </body>
</html>

templates/example_form.html
{% extends "base.html" %}
{% block title %}
  Example Form
{% endblock title %}
{% block meta_description %}
  A page showing what form fields might look like.
{% endblock meta_description %}
{% block content %}
  <h1>Example Form</h1>
  <p>This page shows how multiple form inputs get rendered.</p>
  <p>
    This is meant to be run with `form.as_div`. The div tags contain each field's label, help text, and input/textarea/select/etc.
  </p>
  <p>
    We can target this div container, display as a flexbox column, and standardize the spacing within and between these fields.
  </p>
  <form class="stack" method="post">
    {% csrf_token %}
    {{ form.as_div }}
    <h2>Your Favorite Books</h2>
    {{ book_formset.management_form }}
    {% for book_form in book_formset %}
      <fieldset class="box">
        <legend>Book {{ forloop.counter }}</legend>
        {{ book_form.as_div }}
      </fieldset>
    {% endfor %}
    <button type="submit">Submit</button>
  </form>
{% endblock content %}

templates/home.html
{% extends "base.html" %}
{% block title %}
  Home
{% endblock title %}
{% block content %}
  <h1>djarter</h1>
  <p>A Django starter template including...</p>
  <ul>
    <li>A custom user model with email, no username, and auth views</li>
    <li>CSS layout primitives instead of CSS frameworks</li>
    <li>Django template hot reload</li>
    <li>Formatters and linters ready for pre-commit</li>
    <li>And more!</li>
  </ul>
  {% if user.is_authenticated %}
    <p>Hi {{ user.email }}!</p>
    <p>
      <a href="{% url 'accounts:logout' %}">Log Out</a> |
      <a href="{% url 'accounts:password_change' %}">Change Password</a>
    </p>
  {% else %}
    <p>You are not logged in</p>
    <p>
      <a href="{% url 'accounts:login' %}">Log In</a> |
      <a href="{% url 'accounts:signup' %}">Sign Up</a> |
      <a href="{% url 'accounts:password_reset' %}">Reset Password</a>
    </p>
  {% endif %}
{% endblock content %}

templates/partials/footer.html
<footer class="box invert">
  <p class="font-size:small">
    Started with the <a href="https://github.com/lancegoyke/djarter">djarter</a> template
  </p>
</footer>

templates/partials/header.html
<header class="navbar box invert no-border">
  <p class="site-title">djarter</p>
  <ul class="cluster">
    <li>
      <a href="{% url 'home' %}">Home</a>
      <a href="{% url 'example_form' %}">Example Form</a>
    </li>
  </ul>
</header>